"""Random passphrase generator for connection authentication."""

import random

# Curated word list - tech/nerd themed, easy to read and type
# Single syllable or short words that are unambiguous
WORD_LIST = [
    # Tech/computing
    "byte",
    "code",
    "data",
    "disk",
    "file",
    "grid",
    "hash",
    "heap",
    "link",
    "loop",
    "node",
    "ping",
    "port",
    "root",
    "sync",
    "task",
    "term",
    "unix",
    "wire",
    "chip",
    "bits",
    "boot",
    "core",
    "dump",
    "flag",
    "fork",
    "host",
    "jump",
    "kern",
    "load",
    "mask",
    "null",
    "pack",
    "pipe",
    "push",
    "pull",
    "rack",
    "raid",
    "scan",
    "seed",
    "shell",
    "slot",
    "sort",
    "spam",
    "spool",
    "swap",
    "tree",
    "type",
    # Gaming/nerd culture
    "boss",
    "buff",
    "camp",
    "crit",
    "drop",
    "farm",
    "frag",
    "gear",
    "gold",
    "grind",
    "guild",
    "heal",
    "item",
    "loot",
    "mage",
    "mana",
    "melee",
    "minion",
    "nerf",
    "noob",
    "quest",
    "raid",
    "rogue",
    "spawn",
    "spec",
    "tank",
    "warp",
    "wipe",
    "xp",
    "zone",
    "clan",
    "crew",
    # Sci-fi
    "beam",
    "blast",
    "bolt",
    "clone",
    "cryo",
    "cyber",
    "droid",
    "flux",
    "hyper",
    "ion",
    "laser",
    "mech",
    "nano",
    "nova",
    "orbit",
    "phase",
    "plasma",
    "probe",
    "pulse",
    "quantum",
    "robot",
    "solar",
    "space",
    "star",
    "tech",
    "void",
    "warp",
    "zero",
    "alien",
    "comet",
    "gamma",
    "lunar",
    # Fun/misc nerdy
    "alpha",
    "beta",
    "delta",
    "gamma",
    "omega",
    "sigma",
    "theta",
    "zeta",
    "apex",
    "axiom",
    "base",
    "cube",
    "debug",
    "echo",
    "error",
    "extra",
    "focus",
    "glyph",
    "hex",
    "index",
    "logic",
    "macro",
    "matrix",
    "nexus",
    "octal",
    "pixel",
    "prime",
    "proto",
    "proxy",
    "query",
    "regex",
    "rune",
    "scope",
    "script",
    "signal",
    "stack",
    "static",
    "syntax",
    "token",
    "tuple",
    "vector",
    "vertex",
    "voxel",
    "widget",
    "xpath",
    "yaml",
    "zigzag",
    # Animals (nerdy favorites)
    "fox",
    "owl",
    "wolf",
    "raven",
    "hawk",
    "lynx",
    "panda",
    "cobra",
    "dragon",
    "phoenix",
    "kraken",
    "hydra",
    "sphinx",
    "griffin",
    # Colors (easy to visualize)
    "red",
    "blue",
    "green",
    "cyan",
    "amber",
    "violet",
    "indigo",
    "crimson",
    "azure",
    "jade",
    "onyx",
    "ruby",
    "silver",
    "golden",
    "bronze",
    "copper",
]


def generate_passphrase() -> str:
    """Generate a single random word passphrase."""
    return random.choice(WORD_LIST)


def generate_passphrase_multi(num_words: int = 2, separator: str = "-") -> str:
    """Generate a multi-word passphrase (for future use if needed)."""
    words = random.sample(WORD_LIST, num_words)
    return separator.join(words)


def validate_passphrase(input_passphrase: str, expected_passphrase: str) -> bool:
    """
    Validate a passphrase input against the expected value.
    Case-insensitive comparison with whitespace trimming.
    """
    return input_passphrase.strip().lower() == expected_passphrase.strip().lower()


if __name__ == "__main__":
    # Quick test
    print("Sample passphrases:")
    for _ in range(10):
        print(f"  {generate_passphrase()}")
